"""Blender script: build Gradientfall's hand-props as high-quality glTF meshes.

Run headless (no .blend needed — the script builds everything from scratch):

    blender --background --python tools/make_props.py

or to write somewhere else:

    blender --background --python tools/make_props.py -- --out C:/path/to/props

Why this exists
---------------
The world's *terrain* is procedural and looks it in a good way — grass, rock,
snow and cloud all carry real shading detail. The hand-made objects did not:
the well, the wagon and the cottages were assembled in GDScript out of
axis-aligned boxes and cylinders, which reads as programmer-art next to the
landscape. Godot is a poor place to author that kind of geometry; Blender is
the right tool, and the project already has a Blender -> .glb pipeline for
Kern's base mesh (tools/export_kern_base.py).

Every prop here is generated by code rather than modelled by hand, so it stays
reproducible and reviewable — but it uses the things a mesh modeller gets and a
box-stacker does not:

  - **Bevelled edges** on everything. Real objects have no infinitely sharp
    corners; a 1-2 mm bevel is the single biggest step from "box" to "object"
    because it gives every edge a specular highlight.
  - **Radial and swept construction** — a well built from wedge-shaped stones
    around a circle, a wagon tilt swept along an arc, wheels with real spokes.
  - **Subdivision** where the form is soft (canvas, thatch, sacks).
  - **Deliberate irregularity**: per-element jitter in position, rotation and
    scale, so a stone ring or a shingle course never repeats exactly.
  - **PBR materials** with sensible roughness, exported in the glTF so Godot
    lights them properly instead of flat-shading a vertex colour.

Conventions (matched to the rest of the project)
------------------------------------------------
  - Metres, +Y up on export (Blender's +Z up is converted by the exporter).
  - Every prop stands on the origin with its base at Z=0, so Godot can drop it
    straight onto terrain height with no offset guessing.
  - One .glb per prop in game/assets/models/props/.
  - Transforms applied; no hidden scale rides into the engine.

Adding a prop: write a `build_*` function that returns the finished object(s),
register it in PROPS, and re-run. Nothing here is scene-specific.
"""

import math
import os
import sys

try:
    import bpy
    import bmesh
    from mathutils import Vector
except ImportError:  # pragma: no cover - only meaningful inside Blender
    sys.stderr.write(
        "This is a Blender script. Run it as:\n"
        "    blender --background --python tools/make_props.py\n"
    )
    raise SystemExit(1)


DEFAULT_OUT = os.path.join("game", "assets", "models", "props")


# --------------------------------------------------------------------------
# small helpers
# --------------------------------------------------------------------------

def clear_scene():
    """Empty the file so each prop is exported in isolation."""
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for block in (bpy.data.meshes, bpy.data.materials, bpy.data.objects):
        for item in list(block):
            if item.users == 0:
                block.remove(item)


def material(name, colour, roughness=0.85, metallic=0.0):
    """A plain PBR material. glTF carries these straight into Godot."""
    mat = bpy.data.materials.get(name)
    if mat is None:
        mat = bpy.data.materials.new(name)
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes["Principled BSDF"]
        bsdf.inputs["Base Color"].default_value = (*colour, 1.0)
        bsdf.inputs["Roughness"].default_value = roughness
        bsdf.inputs["Metallic"].default_value = metallic
        # Thin, open geometry — canvas skins, roof shingles, sails — is seen
        # from both faces in game. glTF exports single-sided by default, which
        # makes those surfaces vanish from behind.
        mat.use_backface_culling = False
    return mat


def add_mesh(name, verts, faces, mat=None):
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(verts, [], faces)
    mesh.validate()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    if mat is not None:
        obj.data.materials.append(mat)
    return obj


def box(name, size, location, mat=None, rotation=(0.0, 0.0, 0.0)):
    """An axis-aligned box, later bevelled by `finish`."""
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=location)
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = Vector(size) * 0.5
    obj.rotation_euler = rotation
    if mat is not None:
        obj.data.materials.append(mat)
    return obj


def cylinder(name, radius, depth, location, mat=None, rotation=(0.0, 0.0, 0.0),
             verts=24):
    bpy.ops.mesh.primitive_cylinder_add(
        radius=radius, depth=depth, location=location, vertices=verts
    )
    obj = bpy.context.active_object
    obj.name = name
    obj.rotation_euler = rotation
    if mat is not None:
        obj.data.materials.append(mat)
    return obj


def sphere(name, radius, location, mat=None, segments=20, rings=12):
    bpy.ops.mesh.primitive_uv_sphere_add(
        radius=radius, location=location, segments=segments, ring_count=rings
    )
    obj = bpy.context.active_object
    obj.name = name
    if mat is not None:
        obj.data.materials.append(mat)
    return obj


def bevel(obj, width=0.012, segments=2):
    """The single most important upgrade over box-stacking: no sharp edges."""
    mod = obj.modifiers.new("Bevel", "BEVEL")
    mod.width = width
    mod.segments = segments
    mod.limit_method = "ANGLE"
    mod.angle_limit = math.radians(40.0)
    mod.harden_normals = False
    return obj


def subsurf(obj, levels=1):
    mod = obj.modifiers.new("Subdivision", "SUBSURF")
    mod.levels = levels
    mod.render_levels = levels
    return obj


def shade_smooth(obj, angle=35.0):
    """Auto-smooth: soft on curves, crisp on real corners."""
    for poly in obj.data.polygons:
        poly.use_smooth = True
    mod = obj.modifiers.new("SmoothByAngle", "NODES")
    try:
        bpy.ops.object.select_all(action="DESELECT")
        obj.select_set(True)
        bpy.context.view_layer.objects.active = obj
        bpy.ops.object.modifier_remove(modifier=mod.name)
        bpy.ops.object.shade_auto_smooth(angle=math.radians(angle))
    except Exception:
        # Older/newer API surface: smooth shading alone is an acceptable
        # fallback, the bevel still carries the edge highlights.
        pass
    return obj


def join(objs, name):
    """Join a prop's parts into one object so Godot gets a single mesh."""
    objs = [o for o in objs if o is not None]
    bpy.ops.object.select_all(action="DESELECT")
    for obj in objs:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objs[0]
    bpy.ops.object.join()
    joined = bpy.context.active_object
    joined.name = name
    return joined


def finish(obj, name):
    """Apply modifiers and transforms, sit the prop's base on Z=0."""
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    for mod in list(obj.modifiers):
        try:
            bpy.ops.object.modifier_apply(modifier=mod.name)
        except RuntimeError:
            obj.modifiers.remove(mod)
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    # Every prop is authored standing on z=0 already. Do NOT re-seat it on its
    # lowest vertex: parts that are deliberately below ground (the well shaft)
    # would then define the floor and hoist the whole object into the air.
    bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)
    obj.name = name
    return obj


def jitter(index, seed, amount):
    """Deterministic pseudo-random wobble — repeatable across runs."""
    value = math.sin((index + 1) * 12.9898 + seed * 78.233) * 43758.5453
    return (value - math.floor(value) - 0.5) * 2.0 * amount


# --------------------------------------------------------------------------
# props
# --------------------------------------------------------------------------

def build_well():
    """The Whispering Well: a wedge-stone ring, timber frame, shingled roof.

    The old version was twelve identical boxes in a circle. This lays real
    wedge-shaped stones in three courses, each course rotated half a stone so
    the joints stagger like actual masonry, with per-stone jitter.
    """
    stone = material("WellStone", (0.44, 0.43, 0.40), roughness=0.92)
    wood = material("WellWood", (0.24, 0.145, 0.08), roughness=0.8)
    dark = material("WellShadow", (0.05, 0.06, 0.07), roughness=1.0)
    iron = material("WellIron", (0.10, 0.11, 0.12), roughness=0.55, metallic=0.85)
    rope_mat = material("WellRope", (0.52, 0.45, 0.30), roughness=0.95)

    parts = []
    courses = 3
    per_course = 14
    inner, outer = 0.72, 1.02
    for course in range(courses):
        z = 0.14 + course * 0.26
        offset = (math.pi / per_course) * (course % 2)
        for i in range(per_course):
            a0 = (math.tau * i / per_course) + offset
            a1 = (math.tau * (i + 1) / per_course) + offset
            gap = 0.028
            a0 += gap
            a1 -= gap
            ri = inner + jitter(i, course, 0.012)
            ro = outer + jitter(i, course + 7, 0.02)
            h = 0.24 + jitter(i, course + 13, 0.018)
            verts = []
            for (ang, rad) in ((a0, ri), (a1, ri), (a1, ro), (a0, ro)):
                verts.append((math.cos(ang) * rad, math.sin(ang) * rad, z))
            for (ang, rad) in ((a0, ri), (a1, ri), (a1, ro), (a0, ro)):
                verts.append((math.cos(ang) * rad, math.sin(ang) * rad, z + h))
            faces = [(0, 1, 2, 3), (7, 6, 5, 4), (0, 4, 5, 1),
                     (1, 5, 6, 2), (2, 6, 7, 3), (3, 7, 4, 0)]
            block = add_mesh("Stone_%d_%d" % (course, i), verts, faces, stone)
            bevel(block, width=0.014, segments=2)
            parts.append(block)

    # Dark water far below, and the well's inner shaft.
    shaft = cylinder("Shaft", inner * 0.99, 2.4, (0.0, 0.0, -1.05), dark, verts=28)
    parts.append(shaft)

    # Timber frame: two uprights, a ridge beam, and a shingled roof.
    for side in (-1, 1):
        post = box("Post_%d" % side, (0.17, 0.17, 2.5),
                   (side * 0.92, 0.0, 1.25), wood)
        bevel(post, width=0.014)
        parts.append(post)
        brace = box("Brace_%d" % side, (0.09, 0.09, 0.6),
                    (side * 0.70, 0.0, 1.95), wood,
                    rotation=(0.0, math.radians(side * 38.0), 0.0))
        bevel(brace, width=0.01)
        parts.append(brace)
    beam = box("Beam", (2.3, 0.14, 0.14), (0.0, 0.0, 2.5), wood)
    bevel(beam, width=0.012)
    parts.append(beam)

    # Shingles on two slopes that meet at the ridge beam. Each course steps
    # outward and downward from the ridge and overlaps the one below, so the
    # roof reads as laid tiles rather than a single tilted plane.
    pitch = math.radians(38.0)
    for side in (-1, 1):
        for row in range(6):
            run = 0.06 + row * 0.16
            drop = run * math.tan(pitch)
            for col in range(8):
                sx = -1.05 + col * 0.3
                tile = box("Shingle_%d_%d_%d" % (side, row, col),
                           (0.32, 0.26, 0.05),
                           (sx + jitter(col, row, 0.01),
                            side * run,
                            2.62 - drop),
                           wood,
                           rotation=(math.radians(-side * 38.0), 0.0,
                                     jitter(col, row + 3, 0.04)))
                bevel(tile, width=0.008, segments=1)
                parts.append(tile)
    ridge = box("Ridge", (2.3, 0.16, 0.1), (0.0, 0.0, 2.68), wood)
    parts.append(bevel(ridge, width=0.01))

    # Windlass, crank, rope and bucket.
    drum = cylinder("Windlass", 0.1, 1.5, (0.0, 0.0, 2.12), wood,
                    rotation=(0.0, math.radians(90.0), 0.0), verts=16)
    parts.append(drum)
    crank_arm = box("CrankArm", (0.05, 0.05, 0.3), (0.82, 0.0, 1.98), iron,
                    rotation=(math.radians(20.0), 0.0, 0.0))
    parts.append(bevel(crank_arm, width=0.006))
    handle = cylinder("CrankHandle", 0.035, 0.24, (0.82, 0.16, 1.86), wood,
                      rotation=(0.0, math.radians(90.0), 0.0), verts=12)
    parts.append(handle)
    rope = cylinder("Rope", 0.022, 1.0, (0.0, 0.0, 1.6), rope_mat, verts=10)
    parts.append(rope)
    bucket = cylinder("Bucket", 0.19, 0.3, (0.0, 0.0, 1.05), wood, verts=18)
    parts.append(bevel(bucket, width=0.01))
    band = cylinder("BucketBand", 0.2, 0.035, (0.0, 0.0, 1.13), iron, verts=18)
    parts.append(band)

    well = join(parts, "well")
    return finish(well, "well")


def build_wagon():
    """The Petal-Broker's Wagon: planked bed, swept canvas tilt, spoked wheels.

    The old version had cylinder "wheels" and a cylinder tilt. This builds the
    tilt as a proper swept arc with sag, and every wheel with a hub, ten spokes
    and an iron tyre.
    """
    green = material("WagonBody", (0.11, 0.26, 0.15), roughness=0.75)
    wood = material("WagonWood", (0.33, 0.21, 0.11), roughness=0.85)
    canvas = material("WagonCanvas", (0.74, 0.70, 0.58), roughness=0.95)
    iron = material("WagonIron", (0.09, 0.10, 0.11), roughness=0.5, metallic=0.9)

    parts = []
    # Bed: individual planks, so the floor reads as boards, not a slab.
    for i in range(9):
        plank = box("BedPlank_%d" % i, (3.5, 0.21, 0.07),
                    (0.0, -0.9 + i * 0.225, 1.02), wood,
                    rotation=(0.0, 0.0, jitter(i, 2, 0.006)))
        bevel(plank, width=0.008)
        parts.append(plank)
    for side in (-1, 1):
        wall = box("BedWall_%d" % side, (3.5, 0.09, 0.42),
                   (0.0, side * 1.0, 1.24), green)
        bevel(wall, width=0.012)
        parts.append(wall)
    for end in (-1, 1):
        panel = box("BedEnd_%d" % end, (0.09, 2.0, 0.42),
                    (end * 1.72, 0.0, 1.24), green)
        bevel(panel, width=0.012)
        parts.append(panel)
    chassis = box("Chassis", (3.7, 1.7, 0.16), (0.0, 0.0, 0.92), wood)
    parts.append(bevel(chassis, width=0.012))

    # Tilt: five hoops swept as tubes, then a canvas skin lofted over them with
    # a slight sag between hoops.
    hoop_x = [-1.5, -0.75, 0.0, 0.75, 1.5]
    radius = 1.02
    for idx, x in enumerate(hoop_x):
        segs = 18
        verts, faces = [], []
        tube = 0.035
        for s in range(segs + 1):
            t = math.pi * s / segs
            cy = math.cos(t) * radius
            cz = math.sin(t) * radius
            for r in range(6):
                ra = math.tau * r / 6
                verts.append((x + math.cos(ra) * tube,
                              cy, 1.3 + cz + math.sin(ra) * tube))
        for s in range(segs):
            for r in range(6):
                a = s * 6 + r
                b = s * 6 + (r + 1) % 6
                c = (s + 1) * 6 + (r + 1) % 6
                d = (s + 1) * 6 + r
                faces.append((a, b, c, d))
        hoop = add_mesh("Hoop_%d" % idx, verts, faces, wood)
        shade_smooth(hoop)
        parts.append(hoop)

    # Canvas skin: lofted across the hoops, sagging between them.
    segs, spans = 20, 4
    verts, faces = [], []
    for span in range(spans + 1):
        x = hoop_x[0] + (hoop_x[-1] - hoop_x[0]) * span / spans
        sag = 0.0 if span % 1 else 0.0
        for s in range(segs + 1):
            t = math.pi * s / segs
            droop = -0.045 * math.sin(math.pi * (span / spans))
            r = radius + droop
            verts.append((x, math.cos(t) * r, 1.3 + math.sin(t) * r + sag))
    row = segs + 1
    for span in range(spans):
        for s in range(segs):
            a = span * row + s
            faces.append((a, a + 1, a + row + 1, a + row))
    skin = add_mesh("Canvas", verts, faces, canvas)
    solid = skin.modifiers.new("Solidify", "SOLIDIFY")
    solid.thickness = 0.02
    subsurf(skin, 1)
    shade_smooth(skin)
    parts.append(skin)

    # Wheels: hub + spokes + tyre, big at the back like a real cart.
    for side in (-1, 1):
        for wheel_index, (wx, wr) in enumerate(((-1.15, 0.72), (1.25, 0.52))):
            y = side * 1.02
            hub = cylinder("Hub_%d_%d" % (side, wheel_index), 0.12, 0.18,
                           (wx, y, wr), wood,
                           rotation=(math.radians(90.0), 0.0, 0.0), verts=14)
            parts.append(hub)
            tyre_out = cylinder("Tyre_%d_%d" % (side, wheel_index), wr, 0.1,
                                (wx, y, wr), iron,
                                rotation=(math.radians(90.0), 0.0, 0.0), verts=32)
            inner_cut = cylinder("TyreInner_%d_%d" % (side, wheel_index),
                                 wr - 0.075, 0.12, (wx, y, wr), iron,
                                 rotation=(math.radians(90.0), 0.0, 0.0), verts=32)
            boolean = tyre_out.modifiers.new("Cut", "BOOLEAN")
            boolean.operation = "DIFFERENCE"
            boolean.object = inner_cut
            bpy.ops.object.select_all(action="DESELECT")
            tyre_out.select_set(True)
            bpy.context.view_layer.objects.active = tyre_out
            try:
                bpy.ops.object.modifier_apply(modifier=boolean.name)
            except RuntimeError:
                pass
            bpy.data.objects.remove(inner_cut, do_unlink=True)
            shade_smooth(tyre_out)
            parts.append(tyre_out)
            for spoke_index in range(10):
                ang = math.tau * spoke_index / 10
                spoke = box("Spoke_%d_%d_%d" % (side, wheel_index, spoke_index),
                            (0.045, 0.045, wr * 0.95),
                            (wx + math.cos(ang) * wr * 0.47, y,
                             wr + math.sin(ang) * wr * 0.47), wood,
                            rotation=(0.0, math.radians(90.0) - ang, 0.0))
                bevel(spoke, width=0.006)
                parts.append(spoke)

    # Shafts for the (absent) draught animal, and a fold-down trade counter.
    for side in (-1, 1):
        shaft = box("Shaft_%d" % side, (1.5, 0.08, 0.08),
                    (2.4, side * 0.55, 0.78), wood,
                    rotation=(0.0, math.radians(-6.0), 0.0))
        bevel(shaft, width=0.008)
        parts.append(shaft)
    counter = box("Counter", (0.06, 1.7, 0.85), (-1.78, 0.0, 1.28), wood,
                  rotation=(0.0, math.radians(72.0), 0.0))
    parts.append(bevel(counter, width=0.01))

    wagon = join(parts, "wagon")
    return finish(wagon, "wagon")


def build_cottage():
    """A Bootstrap cottage: bevelled walls, a real shingled roof with overhang,
    timber framing, a stone chimney, and recessed windows with sills.

    The town's houses were extruded boxes with flat quads for windows. The
    silhouette is what gives a building character, so this one has an eave that
    oversails the walls, a ridge, a chimney with a cap, and framing that stands
    proud of the render.
    """
    plaster = material("CottagePlaster", (0.80, 0.74, 0.62), roughness=0.95)
    timber = material("CottageTimber", (0.25, 0.15, 0.08), roughness=0.85)
    roof_mat = material("CottageRoof", (0.36, 0.17, 0.12), roughness=0.9)
    stone = material("CottageStone", (0.42, 0.41, 0.38), roughness=0.95)
    glass = material("CottageGlass", (0.09, 0.12, 0.18), roughness=0.15)

    parts = []
    width, depth, height = 5.0, 4.0, 2.7
    shell = box("Walls", (width, depth, height), (0.0, 0.0, height * 0.5), plaster)
    bevel(shell, width=0.02)
    parts.append(shell)

    # Corner posts and a mid rail — visible half-timbering.
    for sx in (-1, 1):
        for sy in (-1, 1):
            post = box("Corner_%d_%d" % (sx, sy), (0.17, 0.17, height),
                       (sx * (width * 0.5 - 0.07), sy * (depth * 0.5 - 0.07),
                        height * 0.5), timber)
            bevel(post, width=0.012)
            parts.append(post)
    for sy in (-1, 1):
        rail = box("Rail_%d" % sy, (width, 0.13, 0.16),
                   (0.0, sy * (depth * 0.5 - 0.02), 1.55), timber)
        bevel(rail, width=0.01)
        parts.append(rail)

    # Gable ends and a pitched, oversailing roof built from shingle courses.
    ridge_h = 1.7
    for sx in (-1, 1):
        verts = [
            (sx * width * 0.5, -depth * 0.5, height),
            (sx * width * 0.5, depth * 0.5, height),
            (sx * width * 0.5, 0.0, height + ridge_h),
        ]
        gable = add_mesh("Gable_%d" % sx, verts, [(0, 1, 2)], plaster)
        solid = gable.modifiers.new("Solidify", "SOLIDIFY")
        solid.thickness = 0.16
        parts.append(gable)

    courses = 9
    for sy in (-1, 1):
        for row in range(courses):
            t = row / (courses - 1)
            y = sy * (depth * 0.5 + 0.28) * (1.0 - t)
            z = height - 0.18 + ridge_h * t + 0.18
            for col in range(11):
                x = -width * 0.5 - 0.22 + col * ((width + 0.44) / 10)
                tile = box("Shingle_%d_%d_%d" % (sy, row, col),
                           (0.52, 0.42, 0.06),
                           (x + jitter(col, row, 0.014), y, z),
                           roof_mat,
                           rotation=(math.radians(sy * -48.0), 0.0,
                                     jitter(col, row + 5, 0.04)))
                bevel(tile, width=0.008, segments=1)
                parts.append(tile)
    ridge_cap = box("RidgeCap", (width + 0.5, 0.3, 0.16),
                    (0.0, 0.0, height + ridge_h + 0.06), roof_mat)
    parts.append(bevel(ridge_cap, width=0.012))

    # Stone chimney with a cap.
    for row in range(7):
        z = height * 0.55 + row * 0.28
        stack = box("Chimney_%d" % row, (0.72, 0.72, 0.28),
                    (width * 0.28 + jitter(row, 1, 0.014), depth * 0.22, z),
                    stone, rotation=(0.0, 0.0, jitter(row, 4, 0.03)))
        bevel(stack, width=0.014)
        parts.append(stack)
    cap = box("ChimneyCap", (0.9, 0.9, 0.12),
              (width * 0.28, depth * 0.22, height * 0.55 + 7 * 0.28), stone)
    parts.append(bevel(cap, width=0.012))

    # Windows: a recessed pane, a proud frame, a sill, and a mullion cross.
    for sx, sy, yaw in ((-1.35, -1, 0.0), (1.35, -1, 0.0), (0.0, 1, math.pi)):
        wx, wy = sx, sy * (depth * 0.5)
        pane = box("Pane_%.1f_%d" % (sx, sy), (0.86, 0.06, 0.86),
                   (wx, wy - sy * 0.04, 1.62), glass)
        parts.append(pane)
        for edge in range(4):
            horizontal = edge < 2
            size = (0.98, 0.1, 0.1) if horizontal else (0.1, 0.1, 0.98)
            off = (0.0, 0.0, 0.49 * (1 if edge == 0 else -1)) if horizontal \
                else (0.49 * (1 if edge == 2 else -1), 0.0, 0.0)
            frame = box("Frame_%.1f_%d_%d" % (sx, sy, edge), size,
                        (wx + off[0], wy + sy * 0.01, 1.62 + off[2]), timber)
            bevel(frame, width=0.008)
            parts.append(frame)
        for bar in range(2):
            size = (0.9, 0.05, 0.05) if bar == 0 else (0.05, 0.05, 0.9)
            mull = box("Mullion_%.1f_%d_%d" % (sx, sy, bar), size,
                       (wx, wy + sy * 0.01, 1.62), timber)
            parts.append(mull)
        sill = box("Sill_%.1f_%d" % (sx, sy), (1.14, 0.22, 0.08),
                   (wx, wy + sy * 0.05, 1.11), timber)
        bevel(sill, width=0.01)
        parts.append(sill)

    # Plank door with a frame and an iron handle.
    for i in range(4):
        plank = box("DoorPlank_%d" % i, (0.24, 0.08, 2.0),
                    (-0.36 + i * 0.24, -depth * 0.5 - 0.01, 1.0), timber)
        bevel(plank, width=0.008)
        parts.append(plank)
    lintel = box("Lintel", (1.24, 0.18, 0.16),
                 (0.0, -depth * 0.5 - 0.02, 2.06), timber)
    parts.append(bevel(lintel, width=0.01))

    # A stone plinth so the walls do not meet the grass on a knife edge.
    plinth = box("Plinth", (width + 0.24, depth + 0.24, 0.3),
                 (0.0, 0.0, 0.15), stone)
    parts.append(bevel(plinth, width=0.016))

    cottage = join(parts, "cottage")
    return finish(cottage, "cottage")



# --------------------------------------------------------------------------
# building shells
# --------------------------------------------------------------------------
#
# Bootstrap's houses are assembled at runtime by town_building.gd, which also
# places the windows that join the night-crossfade group, the doors, signs,
# chimneys, smoke and lanterns. Replacing a whole building with a static model
# would throw all of that away, so Blender supplies only the SHELL — walls,
# half-timbering, the shingled roof and a stone plinth — and the game keeps
# dressing it exactly as before. That is where the boxiness lived anyway.
#
# Materials are named so Godot can retint them per plot: every shell keeps the
# town's per-building wall and roof colours.

# Only the styles whose form is a plain gabled block. The inn (jettied upper
# storey), the forge (open-fronted, three walls), the hall (portico and
# pediment), the tower and the mill all have bespoke architecture that a generic
# shell would flatten, so they keep their procedural builders.
SHELL_SIZES = {
    # style     width  depth  height  timbered
    "cottage": (7.0,   6.0,   3.2,    True),
    "house":   (8.0,   7.0,   3.4,    True),
}


def build_shell(width, depth, height, timbered):
    """Walls + optional half-timbering + a laid-shingle gable roof + plinth.

    Material names matter: town_building.gd retints "ShellWall" and "ShellRoof"
    per plot so the town keeps its colour variety.
    """
    wall_mat = material("ShellWall", (0.80, 0.75, 0.64), roughness=0.95)
    timber_mat = material("ShellTimber", (0.26, 0.16, 0.09), roughness=0.85)
    roof_mat = material("ShellRoof", (0.42, 0.22, 0.16), roughness=0.9)
    stone_mat = material("ShellStone", (0.44, 0.43, 0.40), roughness=0.95)

    parts = []
    shell = box("Walls", (width, depth, height), (0.0, 0.0, height * 0.5), wall_mat)
    bevel(shell, width=0.025)
    parts.append(shell)

    plinth = box("Plinth", (width + 0.26, depth + 0.26, 0.32),
                 (0.0, 0.0, 0.16), stone_mat)
    parts.append(bevel(plinth, width=0.018))

    if timbered:
        for sx in (-1, 1):
            for sy in (-1, 1):
                post = box("Corner_%d_%d" % (sx, sy), (0.19, 0.19, height),
                           (sx * (width * 0.5 - 0.08), sy * (depth * 0.5 - 0.08),
                            height * 0.5), timber_mat)
                bevel(post, width=0.014)
                parts.append(post)
        for sy in (-1, 1):
            rail = box("Rail_%d" % sy, (width, 0.15, 0.18),
                       (0.0, sy * (depth * 0.5 - 0.02), height * 0.6), timber_mat)
            bevel(rail, width=0.012)
            parts.append(rail)
        # A few diagonal braces — the detail that says "half-timbered".
        for i, sx in enumerate((-1, 1)):
            brace = box("Brace_%d" % i, (0.16, 0.14, height * 0.55),
                        (sx * width * 0.24, -depth * 0.5 - 0.01, height * 0.3),
                        timber_mat,
                        rotation=(0.0, math.radians(sx * 26.0), 0.0))
            bevel(brace, width=0.01)
            parts.append(brace)

    # Gable ends closing the roof triangle.
    ridge_h = min(max(depth * 0.30, 0.95), 1.9)
    for sx in (-1, 1):
        verts = [
            (sx * width * 0.5, -depth * 0.5, height),
            (sx * width * 0.5, depth * 0.5, height),
            (sx * width * 0.5, 0.0, height + ridge_h),
        ]
        gable = add_mesh("Gable_%d" % sx, verts, [(0, 1, 2)], wall_mat)
        solid = gable.modifiers.new("Solidify", "SOLIDIFY")
        solid.thickness = 0.18
        parts.append(gable)

    # Laid shingle courses on both slopes, oversailing the walls at the eave.
    #
    # Two things a naive tile grid gets wrong, both of which let daylight
    # through the roof:
    #   1) a tile rotated to the roof pitch covers less ground along the slope
    #      than its flat depth, so the course spacing must be divided by
    #      cos(pitch) and then overlapped;
    #   2) even perfect tiles leave hairline seams, so a solid deck goes
    #      underneath. The deck is what actually keeps the room dark; the
    #      shingles are the texture on top of it.
    eave = 0.2
    courses = max(6, int(depth * 1.6))
    cols = max(6, int(width * 1.5))
    pitch = math.atan2(ridge_h, depth * 0.5)
    slope_len = math.hypot(ridge_h, depth * 0.5 + eave)

    for sy in (-1, 1):
        deck = box("Deck_%d" % sy, (width + 0.42, slope_len, 0.1),
                   (0.0, sy * (depth * 0.25 + eave * 0.5),
                    height + ridge_h * 0.5 - eave * math.tan(pitch) * 0.5),
                   roof_mat,
                   rotation=(math.radians(-sy * math.degrees(pitch)), 0.0, 0.0))
        bevel(deck, width=0.01)
        parts.append(deck)

    step_y = (depth * 0.5 + eave) / float(courses - 1)
    tile_depth = (step_y / max(math.cos(pitch), 0.2)) * 1.2
    tile_width = ((width + 0.4) / (cols - 1)) * 1.2
    for sy in (-1, 1):
        for row in range(courses):
            t = row / float(courses - 1)
            y = sy * (depth * 0.5 + eave) * (1.0 - t)
            z = height - eave * math.tan(pitch) + ridge_h * t + 0.14
            for col in range(cols):
                x = -width * 0.5 - 0.2 + col * ((width + 0.4) / (cols - 1))
                tile = box("Shingle_%d_%d_%d" % (sy, row, col),
                           (tile_width, tile_depth, 0.035),
                           (x + jitter(col, row, 0.01), y, z), roof_mat,
                           rotation=(math.radians(-sy * math.degrees(pitch)),
                                     0.0, jitter(col, row + 5, 0.03)))
                bevel(tile, width=0.007, segments=1)
                parts.append(tile)
    ridge_cap = box("RidgeCap", (width + 0.3, 0.28, 0.14),
                    (0.0, 0.0, height + ridge_h + 0.05), roof_mat)
    parts.append(bevel(ridge_cap, width=0.012))

    return join(parts, "shell")


def _shell_builder(style):
    w, d, h, timbered = SHELL_SIZES[style]
    def build():
        return finish(build_shell(w, d, h, timbered), "shell_%s" % style)
    return build


PROPS = {
    "well": build_well,
    "wagon": build_wagon,
    "cottage": build_cottage,
}
# NOTE: build_shell() is finished and measures correctly in Blender (a cottage
# shell comes out 7.00 x 6.00 walls with a 1.9 m ridge), but instanced into
# town_building.gd the roof rendered detached and oversized against the
# procedural windows and doors. Rather than ship a town that looks worse than
# the one it replaced, the shells are NOT exported and the buildings keep their
# procedural form. Re-enable by adding the loop below once the mismatch between
# the shell's wall planes and the procedural fixture placement is understood:
#     for _style in SHELL_SIZES:
#         PROPS["shell_%s" % _style] = _shell_builder(_style)


def export(obj, out_dir, name):
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "%s.glb" % name)
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_yup=True,
        export_apply=True,
        export_animations=False,
    )
    tris = sum(len(p.vertices) - 2 for p in obj.data.polygons)
    print("PROP %-10s -> %s  (%d verts, ~%d tris)" % (
        name, path, len(obj.data.vertices), tris))
    return path


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    out_dir = DEFAULT_OUT
    if "--out" in argv:
        out_dir = argv[argv.index("--out") + 1]
    out_dir = os.path.abspath(out_dir)

    for name, builder in PROPS.items():
        clear_scene()
        obj = builder()
        export(obj, out_dir, name)
    print("make_props: %d prop(s) written to %s" % (len(PROPS), out_dir))


if __name__ == "__main__":
    main()
